import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, copyFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { EventEmitter } from 'node:events';

test('native bridge isolates runs, passes argv without a shell, and respects disable', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'openclaw-bridge-'));
  try {
    copyFileSync(new URL('./index.mjs', import.meta.url), join(dir, 'index.mjs'));
    const configFile = join(dir, 'gtrace.json');
    writeFileSync(configFile, '{"enabled":true}');
    const command = join(dir, 'connector with spaces');
    writeFileSync(join(dir, 'runtime.json'), JSON.stringify({ command, configFile }));
    const { registerBridge } = await import(pathToFileURL(join(dir, 'index.mjs')));
    const hooks = new Map(), sent = [];
    let service;
    const launch = (exe, args, options) => {
      assert.equal(exe, command);
      assert.deepEqual(args, ['hook', 'openclaw']);
      assert.equal(options.shell, false);
      const child = new EventEmitter();
      child.stdin = new EventEmitter();
      child.stdin.end = body => { sent.push(JSON.parse(body)); queueMicrotask(() => child.emit('close', 0)); };
      child.kill = () => child.emit('close');
      return child;
    };
    registerBridge({ on: (name, cb) => hooks.set(name, cb), registerService: s => { service = s; } }, launch, () => 2000);
    hooks.get('llm_input')({ runId: 'a', sessionId: 's1', provider: 'test', model: 'small', systemPrompt: 'system', prompt: 'first', historyMessages: [{ role: 'user', content: 'history' }], tools: [{ name: 'read' }] }, {});
    hooks.get('llm_input')({ runId: 'b', sessionId: 's2', prompt: 'second' }, {});
    hooks.get('llm_output')({ runId: 'a', sessionId: 's1', assistantTexts: ['done'], usage: { input: 3 }, reasoningEffort: 'high' }, {});
    hooks.get('model_call_started')({runId:'a',callId:'call-1',provider:'test',model:'small',transport:'sse',headers:{Authorization:'private'}},{});
    hooks.get('model_call_ended')({runId:'a',callId:'call-1',provider:'test',model:'small',durationMs:500,timeToFirstByteMs:125,outcome:'completed',headers:{Authorization:'private'}},{});
    await hooks.get('agent_end')({ runId: 'a', success: true, messages: [] }, { sessionKey: 'alias-s1' });
    assert.equal(sent[0].sessionId, 's1');
    assert.equal(sent[0].prompt, 'first');
    const input = sent[0].observations.find(item => item.kind === 'llm_input').event;
    const output = sent[0].observations.find(item => item.kind === 'llm_output').event;
    const started = sent[0].observations.find(item => item.kind === 'model_call_started').event;
    const ended = sent[0].observations.find(item => item.kind === 'model_call_ended').event;
    assert.equal(input.systemPrompt, 'system');
    assert.equal(input.historyMessages[0].content, 'history');
    assert.equal(input.tools[0].name, 'read');
    assert.equal(output.reasoningEffort, 'high');
    assert.equal(started.transport, 'sse');
    assert.equal(ended.timeToFirstByteMs,125);
    assert.equal(ended.headers,undefined);
    assert.equal(sent[0].observations.length, 4);
    await hooks.get('agent_end')({ runId: 'b', success: true, messages: [] }, {});
    assert.equal(sent[1].prompt, 'second');
    assert.equal(sent[1].observations.length, 1);
    writeFileSync(configFile, '{"enabled":false}');
    await hooks.get('agent_end')({ runId: 'c', success: true }, {});
    assert.equal(sent.length, 2);
    await service.stop();
    writeFileSync(configFile, '{"enabled":true}');
    registerBridge({ on: (name, cb) => hooks.set(name, cb), registerService: () => {} }, () => { throw new Error('secret-command-argument'); });
    await hooks.get('agent_end')({ runId: 'd', success: true }, { sessionId: 's' });
    const logs = readFileSync(join(dir, 'gtrace-hooks.json'), 'utf8');
    const event = JSON.parse(logs.trim());
    assert.equal(event.message, 'bridge failed');
    assert.equal(event.extra.reason, 'spawn failed');
    assert.ok(Number.isFinite(Date.parse(event.ts)));
    assert.ok(!logs.includes('secret-command-argument'));
    // An unwritable logging destination remains fail-open.
    writeFileSync(join(dir, 'runtime.json'), JSON.stringify({ command, configFile, logFile: dir }));
    registerBridge({ on: (name, cb) => hooks.set(name, cb), registerService: () => {} }, () => { throw new Error('private'); });
    await hooks.get('agent_end')({ runId: 'e', success: true }, { sessionId: 's' });
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
